services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_api_core
    ports:
      - "8080:8080"
      - "40000:40000"
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
    depends_on:
      - core-db
      - redis
    networks:
      - network
    volumes:
      - ./logs:/var/log/app-logs

  core-db:
    image: postgres:16
    ports:
      - "5432:5432"
    container_name: docker_database_api
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: redis:latest
    container_name: docker_redis
    ports:
      - "6379:6379"
    networks:
      - network

volumes:
  db_data:

networks:
  network:
    driver: bridge
    name: network
