filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/myapp/*.log 
  json:
    keys_under_root: true
    overwrite_keys: true

output.opensearch:
  hosts: ["https://localhost:9200"]
  username: "username"
  password: "password"
  ssl.verification_mode: "none"
